version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: symfony
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    restart: on-failure
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

